### PR TITLE
fix #23 Extension doesn't work with Geetest on www.kucoin.com

### LINKED ISSUE #23: Extension doesn't work with Geetest on www.kucoin.com
Extension doesn't work with Geetest on https://www.kucoin.com/ucenter/signin. It blocks the captcha loading, but doesn't show extension's solving bar and doesn't start solving, if auto solving is enable. Anti-captcha solves this Geetest successfully.

### PR DESCRIPTION
**Pull request by captcha-solver**

### CODE REVIEW

File: content/captcha/geetest/interceptor.js [hunk 1]
```diff
@@ -40,44 +38,78 @@
...
+                if (params.product === "bind") {
+                    if (typeof captchaObjEvents.onReady === "function") {
+                        captchaObjEvents.onReady(e);
+                    }
+                }
                 return this
             },
             onSuccess: function (e) {
-                captchaObjEvents.onSuccess = e;
+                captchaObjEvents.onSuccessCallback = e;
```
Comment (kratzky) [inline content/captcha/geetest/interceptor.js:112]: `validate.js` is still checking [onSuccess](https://github.com/2captcha/2captcha-solver/blob/d95207c6d8007378643a6a04bb4b7c7c50378fb0/content/captcha/geetest/validate.js#L9) and still calling [`onSuccess`](https://github.com/2captcha/2captcha-solver/blob/d95207c6d8007378643a6a04bb4b7c7c50378fb0/content/captcha/geetest/validate.js#L10), not `onSuccessCallback`

**Review by kratzky — APPROVED** [review]
quickly tested, should work fine
